/**
 * FeatureScaffolder — Writes concrete, ready-to-implement stubs for approved feature proposals.
 *
 * Outputs:
 *  - docs/feature-proposals/YYYY-MM-DD.md  (human-readable report with all proposals)
 *  - A route stub comment block appended to a scratch file (NOT direct edits to routes.ts)
 *
 * The scaffolder intentionally does NOT auto-edit production source files.
 * Instead it generates a ready-to-copy proposal doc and route stubs for dev review.
 */

import fs from "fs";
import path from "path";
import { FeatureProposal } from "./feature-idea-generator";
import { AppSpec } from "./feature-spec-analyzer";
import { spawnNewAgent } from "../agent-supervisor";
import { agentRegistry } from "../agent-registry";

const ROOT = process.cwd();
const PROPOSALS_DIR = path.join(ROOT, "docs", "feature-proposals");

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function formatDate(d: Date): string {
  return d.toISOString().split("T")[0];
}

export async function scaffoldProposals(proposals: FeatureProposal[], spec: AppSpec): Promise<string> {
  ensureDir(PROPOSALS_DIR);

  const today = formatDate(new Date());
  const reportPath = path.join(PROPOSALS_DIR, `${today}.md`);

  const lines: string[] = [
    `# SameVibe Feature Proposals — ${today}`,
    ``,
    `> Generated by FeatureGrowthAgent. Spec captured at ${spec.capturedAt.toISOString()}.`,
    `> ${proposals.length} proposals. Review and promote to backlog as needed.`,
    ``,
  ];

  for (let i = 0; i < proposals.length; i++) {
    const p = proposals[i];
    lines.push(`## ${i + 1}. ${p.title}`);
    lines.push(`**Complexity:** ${p.complexity} | **Target Area:** ${p.targetArea}`);
    lines.push(``);
    lines.push(`### Description`);
    lines.push(p.description);
    lines.push(``);
    lines.push(`### Rationale`);
    lines.push(p.rationale);
    lines.push(``);
    lines.push(`### Affected Files`);
    lines.push(p.affectedFiles.map(f => `- \`${f}\``).join("\n"));
    lines.push(``);

    if (p.requiresNewAgent && p.newAgentDescription) {
      lines.push(`### 🤖 New AI Agent Required`);
      lines.push(p.newAgentDescription);
      lines.push(``);

      // Dynamically spawn the new agent if it doesn't exist yet
      const agentId = `spawned-${p.title.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "").slice(0, 40)}`;
      if (!agentRegistry.get(agentId)) {
        const agentDesc = p.newAgentDescription;
        spawnNewAgent(agentId, p.title + " Agent", "feature-growth", async () => {
          // Spawned agents log their intent; implementation is scaffolded for devs to complete
          console.log(`[SpawnedAgent:${agentId}] Running — purpose: ${agentDesc}`);
          agentRegistry.heartbeat(agentId, { purpose: agentDesc, status: "stub" });
        });
        lines.push(`> ✅ Agent \`${agentId}\` has been auto-registered and is running.`);
        lines.push(``);
      }
    }

    lines.push(`---`);
    lines.push(``);
  }

  lines.push(`## Route Stubs (copy-paste ready)`);
  lines.push(``);
  lines.push("```typescript");
  for (const p of proposals) {
    const slug = p.title.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
    lines.push(`// TODO [${p.title}] — ${p.complexity} complexity`);
    lines.push(`// app.post("/api/${slug}", async (req, res) => {`);
    lines.push(`//   // Implement: ${p.description}`);
    lines.push(`//   res.json({ message: "Not yet implemented" });`);
    lines.push(`// });`);
    lines.push(``);
  }
  lines.push("```");

  fs.writeFileSync(reportPath, lines.join("\n"), "utf-8");
  console.log(`[FeatureScaffolder] 📄 Report written: ${reportPath}`);
  return reportPath;
}

export const featureScaffolder = { scaffoldProposals };
