import { ScrapedEvent } from '../types/scraperTypes.js';

export class FallbackEventScraper {
  /** Generate high-quality local area events positioned within user's 50-mile radius */
  async generateSampleEvents(
    locationName: string,
    keywords: string[],
    userLocation?: { lat: number; lon: number }
  ): Promise<ScrapedEvent[]> {
    const baseLat = userLocation?.lat ?? 40.7608;
    const baseLon = userLocation?.lon ?? -111.8910;
    const now = new Date();

    const sampleEvents: ScrapedEvent[] = [
      {
        title: `Community Tech & AI Meetup`,
        description: `Connect with local developers, founders, and tech enthusiasts. Live demos, discussions on AI, coding, and networking with local creators.`,
        date: new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000 + 19 * 60 * 60 * 1000),
        location: `${locationName} Tech & Innovation Center`,
        latitude: baseLat + 0.012,
        longitude: baseLon - 0.008,
        category: 'Technology',
        sourceUrl: 'https://samevibe.app/events/tech-meetup',
        sourceName: 'Local Area',
        isExternal: true,
        organizerName: 'Tech Alliance',
        price: 0,
        attendeeCount: 42,
        source: 'local',
      },
      {
        title: `Sunset Group Trail Hike & Outdoor Social`,
        description: `Join local outdoor lovers for a group trail hike. Beautiful views, fresh air, and great conversation. All fitness levels welcome!`,
        date: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000 + 18 * 60 * 60 * 1000),
        location: `${locationName} Regional Park & Trailhead`,
        latitude: baseLat + 0.025,
        longitude: baseLon + 0.015,
        category: 'Outdoor & Recreation',
        sourceUrl: 'https://samevibe.app/events/trail-hike',
        sourceName: 'Local Area',
        isExternal: true,
        organizerName: 'Outdoor Explorers',
        price: 0,
        attendeeCount: 28,
        source: 'local',
      },
      {
        title: `Live Acoustic Session & Food Truck Night`,
        description: `Enjoy live acoustic performances by local musicians alongside food trucks and craft drinks in a relaxed social setting.`,
        date: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000 + 20 * 60 * 60 * 1000),
        location: `${locationName} Community Pavilion`,
        latitude: baseLat - 0.015,
        longitude: baseLon + 0.005,
        category: 'Music',
        sourceUrl: 'https://samevibe.app/events/acoustic-night',
        sourceName: 'Local Area',
        isExternal: true,
        organizerName: 'Arts & Music Collective',
        price: 10,
        attendeeCount: 56,
        source: 'local',
      },
      {
        title: `Morning Outdoor Yoga & Social Coffee`,
        description: `Start your weekend with a guided outdoor yoga flow followed by coffee and social chat with fellow health & wellness enthusiasts.`,
        date: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000 + 9 * 60 * 60 * 1000),
        location: `${locationName} Central Park`,
        latitude: baseLat + 0.008,
        longitude: baseLon - 0.012,
        category: 'Health & Wellness',
        sourceUrl: 'https://samevibe.app/events/yoga-coffee',
        sourceName: 'Local Area',
        isExternal: true,
        organizerName: 'Mindful Living Group',
        price: 5,
        attendeeCount: 31,
        source: 'local',
      },
      {
        title: `Creator & Local Artisan Popup Market`,
        description: `Explore unique handcrafted goods, art prints, specialty treats, and local products crafted by neighborhood creators.`,
        date: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000 + 11 * 60 * 60 * 1000),
        location: `${locationName} Town Square Plaza`,
        latitude: baseLat - 0.005,
        longitude: baseLon - 0.018,
        category: 'Arts & Culture',
        sourceUrl: 'https://samevibe.app/events/creator-market',
        sourceName: 'Local Area',
        isExternal: true,
        organizerName: 'Artisan Alliance',
        price: 0,
        attendeeCount: 72,
        source: 'local',
      },
      {
        title: `Weekend Pick-up Sports & Lawn Games`,
        description: `Casual pick-up volleyball, pickleball, and lawn games. Friendly atmosphere, no experience required—just bring your energy!`,
        date: new Date(now.getTime() + 6 * 24 * 60 * 60 * 1000 + 14 * 60 * 60 * 1000),
        location: `${locationName} Sports Complex`,
        latitude: baseLat + 0.018,
        longitude: baseLon + 0.008,
        category: 'Sports & Fitness',
        sourceUrl: 'https://samevibe.app/events/pickup-sports',
        sourceName: 'Local Area',
        isExternal: true,
        organizerName: 'Community Sports Club',
        price: 0,
        attendeeCount: 48,
        source: 'local',
      },
      {
        title: `Foodie Friday: Food Trucks & Pop Culture Trivia`,
        description: `Gather with neighbors for local food trucks, outdoor seating, and casual trivia night. Win prizes and make new friends!`,
        date: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000 + 18 * 60 * 60 * 1000),
        location: `${locationName} Marketplace Hub`,
        latitude: baseLat - 0.020,
        longitude: baseLon + 0.010,
        category: 'Food & Drink',
        sourceUrl: 'https://samevibe.app/events/foodie-friday',
        sourceName: 'Local Area',
        isExternal: true,
        organizerName: 'Neighborhood Eats',
        price: 0,
        attendeeCount: 84,
        source: 'local',
      }
    ];

    return sampleEvents;
  }
}