/**
 * StoreMetadataGenerator — Uses GPT-4o to generate App Store and Play Store listing copy
 * tailored to SameVibe's exact app identity.
 */

import OpenAI from "openai";
import fs from "fs";
import path from "path";

export interface StoreMetadata {
  appStore: {
    title: string;       // max 30 chars
    subtitle: string;    // max 30 chars
    description: string; // max 4000 chars
    keywords: string;    // comma-separated, max 100 chars total
    promotionalText: string; // max 170 chars
  };
  playStore: {
    shortDescription: string; // max 80 chars
    fullDescription: string;  // max 4000 chars
  };
}

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const ROOT = process.cwd();
const META_DIR = path.join(ROOT, "docs", "store-metadata");

export async function generateStoreMetadata(): Promise<StoreMetadata | null> {
  if (!process.env.OPENAI_API_KEY) {
    console.warn("[StoreMetadata] No OPENAI_API_KEY — skipping metadata generation.");
    return null;
  }

  const prompt = `
You are an App Store Optimization (ASO) expert.
Write store listing copy for a mobile app called SameVibe.

About SameVibe:
- Social community mobile app (React Native / Expo)
- Connects people through shared interests, local real-world events, and interest-based communities
- Features: AI-powered matching, community discovery, event attendance, direct messaging, kudos
- Auth via Firebase, payments via Stripe (premium tier)
- Core values: real-world connection, authenticity, local community

Follow these exact character limits:
- App Store title: max 30 chars
- App Store subtitle: max 30 chars
- App Store description: max 4000 chars (be compelling, use line breaks)
- App Store keywords: comma-separated, max 100 chars total
- App Store promotionalText: max 170 chars (shown on store page, seasonal/update-specific)
- Play Store shortDescription: max 80 chars
- Play Store fullDescription: max 4000 chars

Respond ONLY with valid JSON matching this exact structure:
{
  "appStore": {
    "title": "...",
    "subtitle": "...",
    "description": "...",
    "keywords": "...",
    "promotionalText": "..."
  },
  "playStore": {
    "shortDescription": "...",
    "fullDescription": "..."
  }
}
`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [{ role: "user", content: prompt }],
      response_format: { type: "json_object" },
      max_tokens: 2500,
    });

    const raw = response.choices[0]?.message?.content;
    if (!raw) return null;

    const metadata: StoreMetadata = JSON.parse(raw);
    return metadata;
  } catch (err) {
    console.error("[StoreMetadata] OpenAI call failed:", err);
    return null;
  }
}

export function saveStoreMetadata(metadata: StoreMetadata): void {
  if (!fs.existsSync(META_DIR)) fs.mkdirSync(META_DIR, { recursive: true });

  const appStorePath = path.join(META_DIR, "app-store.md");
  const playStorePath = path.join(META_DIR, "play-store.md");

  const appStoreContent = [
    `# App Store Listing — SameVibe`,
    `> Generated by StoreMetadataAgent on ${new Date().toISOString()}`,
    ``,
    `## Title (${metadata.appStore.title.length}/30 chars)`,
    metadata.appStore.title,
    ``,
    `## Subtitle (${metadata.appStore.subtitle.length}/30 chars)`,
    metadata.appStore.subtitle,
    ``,
    `## Promotional Text (${metadata.appStore.promotionalText.length}/170 chars)`,
    metadata.appStore.promotionalText,
    ``,
    `## Keywords (${metadata.appStore.keywords.length}/100 chars)`,
    `\`${metadata.appStore.keywords}\``,
    ``,
    `## Description`,
    metadata.appStore.description,
  ].join("\n");

  const playStoreContent = [
    `# Play Store Listing — SameVibe`,
    `> Generated by StoreMetadataAgent on ${new Date().toISOString()}`,
    ``,
    `## Short Description (${metadata.playStore.shortDescription.length}/80 chars)`,
    metadata.playStore.shortDescription,
    ``,
    `## Full Description`,
    metadata.playStore.fullDescription,
  ].join("\n");

  fs.writeFileSync(appStorePath, appStoreContent, "utf-8");
  fs.writeFileSync(playStorePath, playStoreContent, "utf-8");

  console.log(`[StoreMetadata] 📝 Saved: ${appStorePath}`);
  console.log(`[StoreMetadata] 📝 Saved: ${playStorePath}`);
}

export const storeMetadataGenerator = { generateStoreMetadata, saveStoreMetadata };
